-- MySQL Script generated by MySQL Workbench
-- 02/28/20 20:55:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `tiempoPublicacion` INT NULL COMMENT '',
  PRIMARY KEY (`idTipoUsuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deptos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deptos` (
  `idDeptos` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDeptos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `idDeptos` INT NULL COMMENT '',
  PRIMARY KEY (`idMunicipio`)  COMMENT '',
  INDEX `fk_Municipio_Deptos1_idx` (`idDeptos` ASC)  COMMENT '',
  CONSTRAINT `fk_Municipio_Deptos1`
    FOREIGN KEY (`idDeptos`)
    REFERENCES `mydb`.`Deptos` (`idDeptos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL COMMENT '',
  `primerNombre` VARCHAR(45) NULL COMMENT '',
  `segundoNombre` VARCHAR(45) NULL COMMENT '',
  `primerApellido` VARCHAR(45) NULL COMMENT '',
  `segundoApellido` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `fechaNac` DATETIME NULL COMMENT '',
  `contrasenia` VARCHAR(45) NULL COMMENT '',
  `idTipoUsuario` INT NOT NULL COMMENT '',
  `idMunicipio` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idPersona`)  COMMENT '',
  INDEX `fk_Persona_TipoUsuario1_idx` (`idTipoUsuario` ASC)  COMMENT '',
  INDEX `fk_Persona_Municipio1_idx` (`idMunicipio` ASC)  COMMENT '',
  CONSTRAINT `fk_Persona_TipoUsuario1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `idPersona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTelefono`)  COMMENT '',
  INDEX `fk_Telefono_Persona_idx` (`idPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moneda` (
  `idMoneda` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMoneda`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCategorias`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `caracteristicas` VARCHAR(45) NULL COMMENT '',
  `idCategorias` INT NOT NULL COMMENT '',
  `tipoProducto` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '',
  INDEX `fk_Producto_Categorias1_idx` (`idCategorias` ASC)  COMMENT '',
  CONSTRAINT `fk_Producto_Categorias1`
    FOREIGN KEY (`idCategorias`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anuncios` (
  `idAnuncios` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `precio` DOUBLE NULL COMMENT '',
  `idPersona` INT NOT NULL COMMENT '',
  `idMoneda` INT NOT NULL COMMENT '',
  `idProducto` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idAnuncios`)  COMMENT '',
  INDEX `fk_Anuncios_Persona1_idx` (`idPersona` ASC)  COMMENT '',
  INDEX `fk_Anuncios_Moneda1_idx` (`idMoneda` ASC)  COMMENT '',
  INDEX `fk_Anuncios_Producto1_idx` (`idProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_Anuncios_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncios_Moneda1`
    FOREIGN KEY (`idMoneda`)
    REFERENCES `mydb`.`Moneda` (`idMoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncios_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favoritos` (
  `idFavoritos` INT NOT NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `idPersona` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  PRIMARY KEY (`idFavoritos`)  COMMENT '',
  INDEX `fk_Favoritos_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  INDEX `fk_Favoritos_Persona1_idx` (`idPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Favoritos_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denuncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Denuncias` (
  `idDenuncias` INT NOT NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  `pubDenunciada` INT NULL COMMENT '',
  `razones` VARCHAR(45) NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idDenuncias`)  COMMENT '',
  INDEX `fk_Denuncias_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  CONSTRAINT `fk_Denuncias_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enlaces_Compartidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enlaces_Compartidos` (
  `idEnlace` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `redSocial` VARCHAR(45) NULL COMMENT '',
  `cantidadEnlaces` INT NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idEnlace`)  COMMENT '',
  INDEX `fk_Enlaces_Compartidos_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  CONSTRAINT `fk_Enlaces_Compartidos_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calificacion` (
  `idCalificacion` INT NOT NULL COMMENT '',
  `pubCalificada` INT NULL COMMENT '',
  `puntuacion` VARCHAR(45) NULL COMMENT '',
  `razones` VARCHAR(45) NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `nombre` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCalificacion`)  COMMENT '',
  INDEX `fk_Calificacion_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  INDEX `fk_Calificacion_Persona1_idx` (`nombre` ASC)  COMMENT '',
  CONSTRAINT `fk_Calificacion_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Persona1`
    FOREIGN KEY (`nombre`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensajes` (
  `idMensajes` INT NOT NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `nombre` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMensajes`)  COMMENT '',
  INDEX `fk_Mensajes_Persona1_idx` (`nombre` ASC)  COMMENT '',
  CONSTRAINT `fk_Mensajes_Persona1`
    FOREIGN KEY (`nombre`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificaciones` (
  `idNotificaciones` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `idMensajes` INT NOT NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idNotificaciones`)  COMMENT '',
  INDEX `fk_Notificaciones_Mensajes1_idx` (`idMensajes` ASC)  COMMENT '',
  INDEX `fk_Notificaciones_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  CONSTRAINT `fk_Notificaciones_Mensajes1`
    FOREIGN KEY (`idMensajes`)
    REFERENCES `mydb`.`Mensajes` (`idMensajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificaciones_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FotosAnuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FotosAnuncio` (
  `idFotos` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `urlFoto` VARCHAR(45) NULL COMMENT '',
  `idAnuncios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFotos`)  COMMENT '',
  INDEX `fk_Fotos_Anuncios1_idx` (`idAnuncios` ASC)  COMMENT '',
  CONSTRAINT `fk_Fotos_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `mydb`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FotosUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FotosUsuario` (
  `idFotos` INT NOT NULL COMMENT '',
  `urlFoto` VARCHAR(45) NULL COMMENT '',
  `idPersona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFotos`)  COMMENT '',
  INDEX `fk_FotosUsuario_Persona1_idx` (`idPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_FotosUsuario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
